# Your pipeline definition
trigger:
  branches:
    include:
      - main
      - development

# Define stages, jobs, and steps
stages:
  - stage: Build
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test'
        pool:
          vmImage: 'windows-latest'
        steps:
          # Add your build and test steps here
          - script: echo "Building..."

  - stage: Deployment
    jobs:
      - job: DeployToProduction
        displayName: 'Deploy to Production'
        pool:
          vmImage: 'windows-latest'
        steps:
          # Add your deployment steps here
          - script: echo "Deploying..."

  - stage: DisplayEnvironmentVariablesBash
    jobs:
      - job: ShowVariablesBash
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Displaying Environment Variables using Bash"
              printenv
            displayName: 'Display Environment Variables (Bash)'
